name: Build kernel

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    name: "Building kernel"
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update
          sudo apt install 
          sudo apt install bison flex libssl-dev python3
          sudo apt install libarchive-tools
          bash toolchain_download.sh
          echo "building kernel"
          git submodule update --init --recursive
      - name: Run build
        run: |
          python build_kernel.py --aosp --target=m31 --no-ksu --allow-dirty
      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Image
          path: out/arch/arm64/boot/Image
